create example-node
w3c/vc-jose-cose-test-suite pull request #16
Opened 2024-11-12 20:44 UTC by toteto

This PR adds example implementation for CLI app based on Node

2024-11-13 15:07 UTC, TallTed requested changes
Small fixes, one question (marked by `____`)

2024-11-13 15:07 UTC, TallTed commented on implementations/example-node/README.md
> +This is a example Node implementation CLI wrapper for an implementation. Once the CLI is in place, you can take the command and forward it to an JS library implementation or API endpoint.
```suggestion
This is a example Node implementation of a CLI wrapper for an _____ implementation. Once the CLI is in place, you can take the command and forward it to a JS library implementation or API endpoint.
```

2024-11-13 15:07 UTC, TallTed commented on implementations/example-node/README.md
> +The wrapper exposes `validate` CLI command. If you want to try this locally outside of the Docker environment, navigate to this package `cd implementations/example-node` and run the following command
```suggestion
The wrapper exposes the `validate` CLI command. If you want to try this locally outside of the Docker environment, navigate to this package (e.g., `cd implementations/example-node`), and run the following commands:
```

2024-11-13 15:07 UTC, TallTed commented on implementations/example-node/README.md
> +After this you will be able to run the implementation without the need for Docker
```suggestion
Subsequently, you will be able to run the implementation without needing Docker:
```

2024-11-13 15:07 UTC, TallTed commented on implementations/example-node/README.md
> +Make sure to mount the appropriate directories for input and output files.
~~~suggestion
To run the validator using Docker, mount the appropriate directories for input and output files, and issue a command like the following:

```bash
docker run -v $(pwd)/tests:/tests example-node-validator validate \
  --input /tests/input/valid-credential.json \
  --config '{"check":"identifier"}' \
  --output /tests/output/1-sample-impl.json
```
~~~

2024-11-18 20:58 UTC, toteto commented on implementations/example-node/README.md
> +This is a example Node implementation CLI wrapper for an implementation. Once the CLI is in place, you can take the command and forward it to an JS library implementation or API endpoint.
Something along these lines?

```suggestion
This is a example Node CLI wrapper that can help you integrate either:
- JS library implementation that you should add to the `dependencies` section of `package.json` and import it inside the `main.js`
- Framework agnostic server implementation that is accessible via HTTP API. You can use `fetch` to make the requests.
```

2024-11-18 21:22 UTC, TallTed commented on implementations/example-node/README.md
> +This is a example Node implementation CLI wrapper for an implementation. Once the CLI is in place, you can take the command and forward it to an JS library implementation or API endpoint.
Getting better... What do you think of this?
```suggestion
This is an example Node CLI wrapper that can help you integrate either:
- a JavaScript library implementation that you should add to the `dependencies` section of `package.json` and import inside the `main.js`.
- a Framework-agnostic server implementation that is accessible via HTTP API. You can use `fetch` to make the requests.
```

2024-11-18 21:53 UTC, toteto commented on implementations/example-node/README.md
> +This is a example Node implementation CLI wrapper for an implementation. Once the CLI is in place, you can take the command and forward it to an JS library implementation or API endpoint.
Looks good to me 5ebc557

2024-12-09 19:17 UTC, decentralgabe commented
@antonio-ivanovski thanks for the work! would you mind transferring this PR to https://github.com/decentralgabe/vc-test-suite-template

2024-12-09 19:17 UTC, closed without merging